# converter/text_to_md.py
import logging
import time
import os
import dotenv

from google.api_core import exceptions as google_exceptions
from retry import retry
from concurrent.futures import ThreadPoolExecutor, as_completed

from polytext.processor.transcript_chunker import TranscriptChunker
from polytext.processor.text_merger import TextMerger
from polytext.prompts.text_to_md import TEXT_TO_MARKDOWN_PROMPT, TEXT_PROMPT
from polytext.exceptions import EmptyDocument
from polytext.llm import LLMGenerationError, MultimodalLLM, OPENAI_OUTPUT_ERROR_CODES

dotenv.load_dotenv()


def text_to_md(
    transcript_text: str,
    markdown_output: bool,
    llm_api_key: str,
    save_transcript_chunks: bool,
    model: str = "gemini-3.1-flash-lite",
    model_provider: str = "google",
    timeout_minutes: int | None = None,
) -> dict:
    """
    Transform raw transcript text into Markdown using a language model.

    Args:
        transcript_text (str): The full input transcript text.
        markdown_output (bool): Whether the output should be in Markdown format.
        llm_api_key (str): API key for the LLM provider.
        save_transcript_chunks (bool): Whether to include processed chunk texts in the output.
        model (str): Model used for conversion and chunk merging.
        model_provider (str): Direct LLM provider (``google``/``gemini`` or
            ``openai``).
        timeout_minutes (int | None): Optional provider request timeout in minutes.

    Returns:
        dict: Dictionary with:
            - text (str): Final processed Markdown text.
            - completion_tokens (int): Total number of tokens generated by the model.
            - prompt_tokens (int): Total number of tokens sent in prompts.
            - completion_model (str): Name of the language model used.
            - completion_model_provider (str): Name of the model provider.
            - text_chunks (list, optional): List of intermediate chunks, if requested.
    """
    yt_tr_conv = TextToMdConverter(
        markdown_output=markdown_output,
        llm_api_key=llm_api_key,
        model=model,
        model_provider=model_provider,
        timeout_minutes=timeout_minutes,
    )
    return yt_tr_conv.convert_text_to_md(transcript_text, save_transcript_chunks=save_transcript_chunks)


class TextToMdConverter:
    """Convert chunked raw text to plain text or Markdown with an LLM."""

    def __init__(
        self,
            markdown_output: bool = True,
            llm_api_key: str = None,
            max_llm_tokens: int = 8000,
            prompt_overhead: int = 1000,
            tokens_per_char: float = 0.25,
            overlap_chars: int = 500,
            k: int = 5,
            min_matches: int = 3,
            model: str = "gemini-3.1-flash-lite",
            model_provider: str = "google",
            timeout_minutes: int | None = None,
    ) -> None:
        """
        Initialize the converter with configuration parameters.

        Args:
            markdown_output (bool): Whether output should be in Markdown format.
            llm_api_key (str): Explicit API-key override. If omitted, the
                selected provider SDK uses its environment configuration.
            max_llm_tokens (int): Max token budget per LLM call.
            prompt_overhead (int): Reserved tokens for prompt metadata.
            tokens_per_char (float): Estimated tokens per character.
            overlap_chars (int): Character overlap between chunks.
            k (int): Reserved for future enhancements.
            min_matches (int): Reserved for future enhancements.
            model (str): Model name.
            model_provider (str): Provider of the model.
            timeout_minutes (int | None): Optional provider request timeout in minutes.
        """
        self.markdown_output = markdown_output
        self.llm_api_key = llm_api_key
        self.max_llm_tokens = max_llm_tokens
        self.prompt_overhead = prompt_overhead
        self.tokens_per_char = tokens_per_char
        self.overlap_chars = overlap_chars
        self.k = k
        self.min_matches = min_matches
        self.model = model
        self.model_provider = model_provider
        self.timeout_minutes = timeout_minutes

    def get_client(self) -> object:
        """Create the provider-neutral text generation adapter.

        Returns:
            MultimodalLLM: Adapter configured with this converter's provider,
                model, and optional explicit API key.
        """
        return MultimodalLLM(
            model=self.model,
            provider=self.model_provider,
            api_key=self.llm_api_key,
            timeout_minutes=self.timeout_minutes if self.model_provider == "openai" else None,
        )

    def get_prompt_template(self) -> str:
        """
        Select appropriate prompt template based on output format.

        Returns:
            str: The selected prompt template.
        """
        if self.markdown_output:
            logging.info("Using prompt for markdown format")
            return TEXT_TO_MARKDOWN_PROMPT
        else:
            logging.info("Using prompt for plain text format")
            return TEXT_PROMPT

    @retry(
        (
            google_exceptions.DeadlineExceeded,
            google_exceptions.ResourceExhausted,
            google_exceptions.ServiceUnavailable,
            google_exceptions.InternalServerError,
        ),
        tries=5,
        delay=2,
        backoff=2,
    )
    def process_chunk(self, client: object,
        prompt_template: str,
        chunk_text: str,
        index: int) -> dict:
        """
        Send a chunk of text to the LLM for processing.

        Args:
            client (object): The GenAI client instance.
            prompt_template (str): Prompt template to guide the model.
            chunk_text (str): The text chunk to process.
            index (int): Index of the chunk (used for logging and ordering).

        Returns:
            dict: A dictionary with processed transcript and token usage.

        Raises:
            Exception: If the LLM call fails.
        """
        logging.info(f"Processing chunk {index + 1}...")

        start_time = time.time()

        try:
            response = client.generate_text(
                instructions=prompt_template,
                input_text=chunk_text,
                max_output_tokens=self.max_llm_tokens,
            )
        except LLMGenerationError as error:
            error_code = OPENAI_OUTPUT_ERROR_CODES.get(error.reason)
            if self.model_provider != "openai" or error_code is None:
                raise
            logging.warning(
                "OpenAI text chunk returned unusable output: index=%s model=%s reason=%s prompt_tokens=%s completion_tokens=%s partial_output=%r",
                index,
                self.model,
                error.reason,
                error.prompt_tokens,
                error.completion_tokens,
                error.partial_text,
            )
            raise EmptyDocument(
                message=f"OpenAI text processing returned unusable output ({error.reason}) for chunk {index + 1}",
                code=error_code,
            ) from error

        elapsed = time.time() - start_time
        logging.info(f"Chunk {index + 1} processed in {elapsed:.2f}s")

        return {
            "transcript": response.text,
            "completion_tokens": response.completion_tokens,
            "prompt_tokens": response.prompt_tokens,
        }


    def convert_text_to_md(self, transcript_text: str,
        save_transcript_chunks: bool = False) -> dict:
        """
        Chunk the transcript, process each chunk in parallel, and merge results.

        Args:
            transcript_text (str): The full input transcript to convert.
            save_transcript_chunks (bool, optional): Whether to include intermediate chunk outputs in the result.

        Returns:
            dict: Dictionary with:
                - text (str): Final merged output.
                - completion_tokens (int): Total tokens generated by the model.
                - prompt_tokens (int): Total tokens used in prompts.
                - completion_model (str): Model name used.
                - completion_model_provider (str): Provider name.
                - text_chunks (list, optional): List of individual processed chunks.
        """
        chunker = TranscriptChunker(
            transcript=transcript_text,
            max_llm_tokens=self.max_llm_tokens,
            prompt_overhead=self.prompt_overhead,
            tokens_per_char=self.tokens_per_char,
            overlap_chars=self.overlap_chars,
        )

        logging.info("**** Initial chunking ****")
        chunks = chunker.chunk_transcript()
        logging.info(f"***** Transcript split into {len(chunks)} chunks. *****")

        client = self.get_client()
        prompt_template = self.get_prompt_template()

        results = []
        total_completion_tokens = 0
        total_prompt_tokens = 0

        with ThreadPoolExecutor() as executor:
            future_to_index = {
                executor.submit(self.process_chunk, client, prompt_template, chunk["text"], chunk["index"]): chunk["index"]
                for chunk in chunks
            }

            for future in as_completed(future_to_index):
                index = future_to_index[future]
                result = future.result()
                results.append((index, result["transcript"]))
                total_completion_tokens += result["completion_tokens"]
                total_prompt_tokens += result["prompt_tokens"]

        # Sort results by index and extract the processed text
        transcript_chunks = [t[1] for t in sorted(results, key=lambda x: x[0])]

        # Merge all processed chunks into one final result
        text_merger = TextMerger(
            completion_model=self.model,
            completion_model_provider=self.model_provider,
            llm_api_key=self.llm_api_key,
            timeout_minutes=self.timeout_minutes,
        )
        final_text = text_merger.merge_chunks_with_llm_sequential(chunks=transcript_chunks)

        result_dict = {
            "text": final_text["full_text_merged"],
            "completion_tokens": total_completion_tokens + final_text["completion_tokens"],
            "prompt_tokens": total_prompt_tokens + final_text["prompt_tokens"],
            "completion_model": self.model,
            "completion_model_provider": self.model_provider,
        }

        if save_transcript_chunks:
            result_dict["text_chunks"] = transcript_chunks

        logging.info(f"**** FINISH ****")

        return result_dict
